### PR TITLE
[MRG] Add CI pipeline + unit test

### PR DESCRIPTION
**Pull request by MartinThoma**

### CODE REVIEW

**Comment by MartinThoma** [comment]
I know the unit test is not super helpful, but maybe with the initial testing setup being there, it's easier to add new tests :-) 

(I could also add linting, but then I would really recommend using the autoformatter black ... and I know that some projects don't want to use autoformatters)

**Comment by MartinThoma** [comment]
I could also add type checking with mypy if you want?

**Comment by vinayak-mehta** [comment]
Thanks for working on this pull request!

> I know the unit test is not super helpful, but maybe with the initial testing setup being there, it's easier to add new tests :-)

It _is_ super helpful! Like you pointed out, this makes it easy to add new tests! :smile: 

> (I could also add linting, but then I would really recommend using the autoformatter black ... and I know that some projects don't want to use autoformatters)

An autoformatter would be awesome! You can add `black`. :+1: 

> I could also add type checking with mypy if you want?

I haven't used mypy a lot, would type checking be useful here? Does it also require the code to have type hints?

Also, instead of adding new requirement files, I think we can just add dev requirements to the `setup.py`: https://github.com/camelot-dev/excalibur/blob/master/setup.py#L26 and use `pip install -e ".[dev]"` inside the workflow. We can also drop 3.5 and test on 3.6, 3.7, and 3.8.

Thanks again for working on this pull request!

**Comment by MartinThoma** [comment]
> An autoformatter would be awesome! You can add black. +1

Awesome! I'll do that in a separate PR as the first application of black usually makes it impossible to spot any other changes :-)

**Comment by MartinThoma** [comment]
> I  haven't used mypy a lot, would type checking be useful here? Does it also require the code to have type hints?

I've just added it in another Commit so that you can have a look. [I love type checking](https://medium.com/analytics-vidhya/type-annotations-in-python-3-8-3b401384403d) for two reasons: (1) It is documentation for function input / output and thus helps a lot to understand the code and (2) it catches errors once in a while, e.g. None values where you thought you would receive another value. And while doing that, it does not require a lot of effort and doesn't change the code too much. It has a nice learning curve to grow into it. It's not necessary to annotate everything right from the start, as my PR shows.

Because you still support Python 3.5, I've used the comment-annotation syntax. I think from Python 3.6 on one can use "proper" annotations.

**Comment by MartinThoma** [comment]
> Also, instead of adding new requirement files, I think we can just add dev requirements to the setup.py: https://github.com/camelot-dev/excalibur/blob/master/setup.py#L26 and use pip install -e ".[dev]" inside the workflow. We can also drop 3.5 and test on 3.6, 3.7, and 3.8.

Dropping 3.5 and adding 3.8 (and potentially 3.9?) sounds good, but I'd do that in another PR :-) 

I can add another extra requirement in the setup.py, but I would keep the pinned dependencies for testing. This makes the test runs deterministic. It prevents the tests from failing with an unrelated change (that's always the most frustrating part to me when I add code to a new project - if I have to suddenly take care of a lot of completely unrelated stuff, simply because the pipeline breaks). Also, I think of the extra requirements as a feature for the users. I usually try to keep them clean from stuff the user should not need to care about.

I like to specify abstract dependencies in the `.in` file and use `pip-compile` from [`pip-tools`](https://github.com/jazzband/pip-tools) to pin those and the transitive dependencies as well.

What do you think? Would you still prefer both requirement files to be removed?

**Comment by vinayak-mehta** [comment]
> Awesome! I'll do that in a separate PR as the first application of black usually makes it impossible to spot any other changes :-)

Makes sense!

> I can add another extra requirement in the setup.py, but I would keep the pinned dependencies for testing. This makes the test runs deterministic. It prevents the tests from failing with an unrelated change (that's always the most frustrating part to me when I add code to a new project - if I have to suddenly take care of a lot of completely unrelated stuff, simply because the pipeline breaks). Also, I think of the extra requirements as a feature for the users. I usually try to keep them clean from stuff the user should not need to care about.

I like the tests being deterministic as I've faced similar problems in the past. It makes sense to use `pip-tools` to pin requirements for tests. I guess I should start using it for other projects too!

**Comment by vinayak-mehta** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Pull request merged**
