### PR TITLE
[MRG] Open webapp automatically in default browser

### LINKED ISSUE #109: Open Excalibur in default browser
Please open a browser window with Excalibur on startup. This is most common usability feature that would really nice to have.  

This could be implemented using [click.launch](https://click.palletsprojects.com/en/7.x/api/#click.launch) or [webbrowser](https://docs.python.org/3/library/webbrowser.html) module.

### PR DESCRIPTION
**Pull request by vinayak-mehta**
Closes #109

### CODE REVIEW

**Comment by vinayak-mehta** [comment]
@arky Does this look good to you? It works for me on Linux. How do we test for Windows? I'm not sure if `click.launch` is cross-platform, it could be as most click functionality is.

**Comment by arky** [comment]
@vinayak-mehta Could you generate a build for this PR? The simplest thing to do is tested the Github action artifacts on windows. We could reachout to the community to download the executables and test them.

**Comment by arky** [comment]
@vinayak-mehta Sorry for the delay, I have tested this on Windows 32bit machine with Python 3. Launching excalibur with open the default system browser as expected. 

Good for the merge.

**Comment by arky** [comment]
Also tested on Ubuntu LTS, works as expected.

**Pull request merged**
