### PR TITLE
[MRG] Fix issue #43

### PR DESCRIPTION
**Pull request by vm-asd2015**
Fix issue #43: close_fds incompatibility on windows platform.

### CODE REVIEW

**Review by bosd — APPROVED** [review]
LGTM!

**Comment by bosd** [comment]
@foarsitter Do you have super powers here?
cc @MartinThoma 
Who are the maintainers here?

**Comment by foarsitter** [comment]
Sure, I have. But I would be a blind merge from my side.

**Comment by bosd** [comment]
Are you ok with that? Any progress is welcomed and better then nothing at this state of the project.

Kindly look into the repo settings so that new PR's can be made.

**Pull request merged**
