### PR TITLE
[MRG] Remove Python 3.5 support/apply black+isort+pre-commit

### PR DESCRIPTION
**Pull request by MartinThoma**
Add Python 3.8 support

### CODE REVIEW

**Comment by MartinThoma** [comment]
The Flake8 checks revealed a bug: `./excalibur/utils/task.py:35:28: F821 undefined name 'self'`

**Comment by MartinThoma** [comment]
I've added a couple of things:

* CI/CD: Black-check, flake8-check
* Flake8: Some plugins
    * bugbear often points out problematic code
    * comprehensions improve list comprehensions (e.g. tell you when you could use a generator instead)
    * flake8_implicit_str_concat tells you things like `"foo"  "bar"` can be replaced by `"foobar"` (happens sometimes with black)
* [pre-commit](https://towardsdatascience.com/pre-commit-hooks-you-must-know-ff247f5feb7e) ([isort](https://github.com/PyCQA/isort), making sure files and with `\n` so that diffs are nicer)

Let me know if you dislike some of them, then I'll undo it :-)

**Comment by vinayak-mehta** [comment]
> The Flake8 checks revealed a bug: ./excalibur/utils/task.py:35:28: F821 undefined name 'self'

That's awesome! I've fixed this on master.

> I've added a couple of things: [...]

All of these things look super useful! Can we just ignore changes to imports and js/css files for now? I like the way imports are sorted based on length right now.

**Comment by vinayak-mehta** [comment]
Thank you for working on this PR!

**Comment by vinayak-mehta** [comment]
@MartinThoma This looks good to me! Are you working on any other changes? Otherwise I can merge it.

**Comment by MartinThoma** [comment]
Form my side it's fine :-) I've now changed isort to use lenght-sorting, but if you prefer I can also remove that :-)

**Comment by vinayak-mehta** [comment]
Length sorting looks good!

**Comment by vinayak-mehta** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Pull request merged**
